parameters:

    #
    # Repositories
    #
    elcodi.core.page.repository.page.class: Elcodi\Component\Page\Repository\PageRepository

    #
    # Factories
    #
    elcodi.core.page.factory.page.class: Elcodi\Component\Page\Factory\PageFactory

    #
    # Controllers
    #
    elcodi.core.page.controller.page.class: Elcodi\Component\Page\Controller\PageController

    #
    # Loaders
    #
    elcodi.core.page.router.simple_loader.class: Elcodi\Component\Page\Router\PageRouterSimpleLoader

    #
    # Renderers
    #
    elcodi.core.page.chain_renderer.class: Elcodi\Component\Page\Renderer\ChainPageRenderer
