services:

    #
    # Controllers
    #
    elcodi.core.page.controller.page:
        class: %elcodi.core.page.controller.page.class%
        arguments:
            page_repository: @elcodi.repository.page
            request_stack: @request_stack
