services:

    #
    # Controllers
    #
    elcodi.core.page.controller.page:
        class: %elcodi.controller.page.class%
        arguments:
            - @elcodi.repository.page
            - @request_stack
            - @elcodi.core.page.chain_renderer
