services:

    #
    # Factories
    #

    #
    # Factory for entity page
    #
    elcodi.factory.page:
        class: %elcodi.factory.page.class%
        calls:
            - [setEntityNamespace, [%elcodi.core.page.entity.page.class%]]
