services:

    #
    # Factories
    #

    #
    # Factory for entity page
    #
    elcodi.core.page.factory.page:
        class: %elcodi.core.page.factory.page.class%
        calls:
            - [setEntityNamespace, [%elcodi.core.page.entity.page.class%]]

    elcodi.factory.page:
        alias: elcodi.core.page.factory.page
