services:

    #
    # Router simple loader
    #
    elcodi.core.page.router.simple_loader.loader:
        class: Elcodi\Component\Core\Router\SingleRouterLoader
        arguments:
            - %elcodi.core.page.routing.route_name%
            - %elcodi.core.page.routing.route_path%
            - %elcodi.core.page.routing.controller%
            - 'elcodi_page_render'
            -
                path: '[^/]+(?>/[^/]+)*+'
