services:

    #
    # Router simple loader
    #
    elcodi.core.page.router.simple_loader.loader:
        class: %elcodi.core.page.router.simple_loader.class%
        arguments:
            - %elcodi.core.page.routing.route_name%
            - %elcodi.core.page.routing.route_path%
            - %elcodi.core.page.routing.controller%
