services:

    #
    # Object Managers
    #
    elcodi.object_manager.page:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.page.entity.page.class%
