services:

    #
    # Repositories
    #

    #
    # Repository for entity page
    #
    elcodi.repository.page:
        parent: elcodi.abstract_repository
        class: %elcodi.core.page.repository.page.class%
        arguments: [ %elcodi.core.page.entity.page.class% ]
